default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: rails
  password: rails
  host: localhost

development:
  <<: *default
  database: testable_demo

test:
  <<: *default
  database: testable_demo_test